trainer:
  max_epochs: -1
  accelerator: gpu
  devices: 1
  val_check_interval: 50
  log_every_n_steps: 50
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 100
